spring.application.name=InventoryMgtSystem
server.port=5050

# POSTGRESQL CONNECTION (Neon)
spring.datasource.url=jdbc:postgresql://ep-muddy-fire-ahyzjjis-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_4vTciCQ9SlVH&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4vTciCQ9SlVH
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


#THE MAXIMUM SIGN OF IMAGE THAT CAN BE UPLOADED
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
secreteJwtString=phegondev123456789phegondev123456789

# REDIS CONNECTION (Upstash)
spring.data.redis.url=rediss://default:gQAAAAAAAWV3AAIgcDE5ZGQzOWI3OGJkYjU0NThkYjIzNmRiNzAyNDFkYjIzMQ@mutual-bengal-91511.upstash.io:6379
